// This file is auto-generated by @hey-api/openapi-ts

export const APACRegionSchema = {
    type: 'string',
    enum: ['Vietnam', 'Thailand', 'Southeast Asia', 'Greater China', 'North Asia', 'South Asia', 'Australia / Pacific', 'Europe', 'Americas', 'Middle East & Africa'],
    title: 'APACRegion'
} as const;

export const ActivitiesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ActivityPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ActivitiesPublic'
} as const;

export const ActivityCreateSchema = {
    properties: {
        activity_type: {
            '$ref': '#/components/schemas/ActivityType',
            default: 'Meeting'
        },
        date: {
            type: 'string',
            maxLength: 20,
            title: 'Date'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: ['date'],
    title: 'ActivityCreate'
} as const;

export const ActivityPublicSchema = {
    properties: {
        activity_type: {
            '$ref': '#/components/schemas/ActivityType',
            default: 'Meeting'
        },
        date: {
            type: 'string',
            maxLength: 20,
            title: 'Date'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['date', 'id', 'created_by_id'],
    title: 'ActivityPublic'
} as const;

export const ActivityTypeSchema = {
    type: 'string',
    enum: ['Meeting', 'Dinner', 'Site visit', 'Phone call', 'WhatsApp summary', 'Proposal sent', 'NDA signed', 'LOI signed', 'HMA signed', 'Pre-opening review', 'Other'],
    title: 'ActivityType'
} as const;

export const Body_documents_upload_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        doc_type: {
            type: 'string',
            title: 'Doc Type',
            default: 'Other'
        },
        permission: {
            type: 'string',
            title: 'Permission',
            default: 'Internal Only'
        },
        deal_id: {
            type: 'string',
            title: 'Deal Id',
            default: ''
        },
        deal_name: {
            type: 'string',
            title: 'Deal Name',
            default: ''
        },
        version: {
            type: 'string',
            title: 'Version',
            default: 'v1.0'
        },
        note: {
            type: 'string',
            title: 'Note',
            default: ''
        },
        is_confidential: {
            type: 'boolean',
            title: 'Is Confidential',
            default: false
        }
    },
    type: 'object',
    required: ['file', 'name'],
    title: 'Body_documents-upload_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CatchupStatusSchema = {
    type: 'string',
    enum: ['On track', 'Due this week', 'Overdue', 'No cadence'],
    title: 'CatchupStatus'
} as const;

export const ContactStrengthSchema = {
    type: 'string',
    enum: ['New', 'Warm', 'Strong'],
    title: 'ContactStrength'
} as const;

export const DealAuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        field: {
            type: 'string',
            title: 'Field'
        },
        old_value: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Old Value'
        },
        new_value: {
            type: 'string',
            title: 'New Value'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'field', 'old_value', 'new_value', 'note', 'user_id', 'created_at'],
    title: 'DealAuditLogPublic'
} as const;

export const DealCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        deal_type: {
            '$ref': '#/components/schemas/DealType',
            default: 'HMA'
        },
        country: {
            type: 'string',
            maxLength: 100,
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/APACRegion'
                },
                {
                    type: 'null'
                }
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        project_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectType'
                },
                {
                    type: 'null'
                }
            ]
        },
        stage: {
            '$ref': '#/components/schemas/DealStage',
            default: 'Lead'
        },
        opening_target: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opening Target'
        },
        keys: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Keys'
        },
        probability: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Probability'
        },
        pipeline_value: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pipeline Value'
        },
        fee_forecast: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fee Forecast'
        },
        risk: {
            '$ref': '#/components/schemas/DealRisk',
            default: 'Green'
        },
        feasibility: {
            '$ref': '#/components/schemas/DealFeasibility',
            default: 'TBD'
        },
        next_action: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Action'
        },
        bd_owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bd Owner Id'
        }
    },
    type: 'object',
    required: ['name', 'country'],
    title: 'DealCreate'
} as const;

export const DealFeasibilitySchema = {
    type: 'string',
    enum: ['TBD', 'Weak', 'Medium', 'Strong', 'Updated'],
    title: 'DealFeasibility'
} as const;

export const DealPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        deal_type: {
            '$ref': '#/components/schemas/DealType',
            default: 'HMA'
        },
        country: {
            type: 'string',
            maxLength: 100,
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/APACRegion'
                },
                {
                    type: 'null'
                }
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        project_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectType'
                },
                {
                    type: 'null'
                }
            ]
        },
        stage: {
            '$ref': '#/components/schemas/DealStage',
            default: 'Lead'
        },
        opening_target: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opening Target'
        },
        keys: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Keys'
        },
        probability: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Probability'
        },
        pipeline_value: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pipeline Value'
        },
        fee_forecast: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fee Forecast'
        },
        risk: {
            '$ref': '#/components/schemas/DealRisk',
            default: 'Green'
        },
        feasibility: {
            '$ref': '#/components/schemas/DealFeasibility',
            default: 'TBD'
        },
        next_action: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Action'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        deal_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Number'
        },
        bd_owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bd Owner Id'
        },
        bd_owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bd Owner Name'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        days_in_stage: {
            type: 'integer',
            title: 'Days In Stage',
            default: 0
        },
        stage_changed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stage Changed At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        project_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Name'
        },
        project_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Number'
        }
    },
    type: 'object',
    required: ['name', 'country', 'id', 'created_by_id'],
    title: 'DealPublic'
} as const;

export const DealRiskSchema = {
    type: 'string',
    enum: ['Green', 'Amber', 'Red'],
    title: 'DealRisk'
} as const;

export const DealStageSchema = {
    type: 'string',
    enum: ['Lead', 'NDA / Qualified', 'Feasibility', 'Proposal', 'Negotiation', 'LOI Signed', 'HMA Signed', 'Pre-opening', 'Opened', 'Lost'],
    title: 'DealStage'
} as const;

export const DealTypeSchema = {
    type: 'string',
    enum: ['HMA', 'TSA', 'Franchise', 'Consulting', 'Pre-opening', 'Other'],
    title: 'DealType'
} as const;

export const DealUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/APACRegion'
                },
                {
                    type: 'null'
                }
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand'
        },
        project_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectType'
                },
                {
                    type: 'null'
                }
            ]
        },
        opening_target: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opening Target'
        },
        keys: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Keys'
        },
        probability: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Probability'
        },
        pipeline_value: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pipeline Value'
        },
        fee_forecast: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fee Forecast'
        },
        risk: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DealRisk'
                },
                {
                    type: 'null'
                }
            ]
        },
        feasibility: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DealFeasibility'
                },
                {
                    type: 'null'
                }
            ]
        },
        next_action: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Action'
        },
        bd_owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bd Owner Id'
        }
    },
    type: 'object',
    title: 'DealUpdate'
} as const;

export const DealsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DealPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DealsPublic'
} as const;

export const DocPermissionSchema = {
    type: 'string',
    enum: ['Internal Only', 'Shared with Owner', 'Restricted'],
    title: 'DocPermission'
} as const;

export const DocTypeSchema = {
    type: 'string',
    enum: ['NDA', 'Proposal', 'Feasibility', 'HMA Draft', 'Contract', 'Technical Drawings', 'Legal Document', 'Presentation', 'Other'],
    title: 'DocType'
} as const;

export const DocumentPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        doc_type: {
            '$ref': '#/components/schemas/DocType',
            default: 'Other'
        },
        permission: {
            '$ref': '#/components/schemas/DocPermission',
            default: 'Internal Only'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        version: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version',
            default: 'v1.0'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        is_confidential: {
            type: 'boolean',
            title: 'Is Confidential',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        original_filename: {
            type: 'string',
            title: 'Original Filename'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        uploaded_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Uploaded By Id'
        },
        uploaded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uploaded At'
        },
        download_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Download Url'
        },
        can_view: {
            type: 'boolean',
            title: 'Can View',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'id', 'original_filename', 'file_size', 'content_type', 'uploaded_by_id'],
    title: 'DocumentPublic'
} as const;

export const DocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DocumentsPublic'
} as const;

export const FeasibilitySnapshotCreateSchema = {
    properties: {
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        assumptions: {
            type: 'string',
            title: 'Assumptions'
        },
        outputs: {
            type: 'string',
            title: 'Outputs'
        }
    },
    type: 'object',
    required: ['assumptions', 'outputs'],
    title: 'FeasibilitySnapshotCreate'
} as const;

export const FeasibilitySnapshotPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        label: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        assumptions: {
            type: 'string',
            title: 'Assumptions'
        },
        outputs: {
            type: 'string',
            title: 'Outputs'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'deal_id', 'deal_name', 'label', 'assumptions', 'outputs', 'created_by_id', 'created_at'],
    title: 'FeasibilitySnapshotPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InteractionTypeSchema = {
    type: 'string',
    enum: ['Meeting', 'Dinner', 'Site visit', 'Phone call', 'WhatsApp summary', 'Proposal sent', 'NDA signed', 'Other'],
    title: 'InteractionType'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MasterDataCreateSchema = {
    properties: {
        category: {
            type: 'string',
            title: 'Category'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        }
    },
    type: 'object',
    required: ['category', 'value'],
    title: 'MasterDataCreate'
} as const;

export const MasterDataPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'category', 'value', 'sort_order', 'is_active'],
    title: 'MasterDataPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MilestoneCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        department: {
            '$ref': '#/components/schemas/MilestoneDept',
            default: 'Ops'
        },
        milestone_owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Milestone Owner'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        status: {
            '$ref': '#/components/schemas/MilestoneGate',
            default: 'Green'
        },
        blocker: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blocker'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'MilestoneCreate'
} as const;

export const MilestoneDeptSchema = {
    type: 'string',
    enum: ['Ops', 'IT', 'Finance', 'Design', 'Legal', 'Procurement', 'HR', 'Marketing'],
    title: 'MilestoneDept'
} as const;

export const MilestoneGateSchema = {
    type: 'string',
    enum: ['Green', 'Amber', 'Red'],
    title: 'MilestoneGate'
} as const;

export const MilestonePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        department: {
            '$ref': '#/components/schemas/MilestoneDept',
            default: 'Ops'
        },
        milestone_owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Milestone Owner'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        status: {
            '$ref': '#/components/schemas/MilestoneGate',
            default: 'Green'
        },
        blocker: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blocker'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_by_id'],
    title: 'MilestonePublic'
} as const;

export const MilestoneUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        department: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MilestoneDept'
                },
                {
                    type: 'null'
                }
            ]
        },
        milestone_owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Milestone Owner'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MilestoneGate'
                },
                {
                    type: 'null'
                }
            ]
        },
        blocker: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blocker'
        }
    },
    type: 'object',
    title: 'MilestoneUpdate'
} as const;

export const MilestonesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MilestonePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MilestonesPublic'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OwnerContactCreateSchema = {
    properties: {
        fusion_role: {
            type: 'string',
            maxLength: 100,
            title: 'Fusion Role'
        },
        owner_contact: {
            type: 'string',
            maxLength: 100,
            title: 'Owner Contact'
        },
        contact_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Title'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        seniority: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seniority'
        },
        strength: {
            '$ref': '#/components/schemas/ContactStrength',
            default: 'New'
        },
        last_met: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Met'
        },
        senior_flag: {
            type: 'boolean',
            title: 'Senior Flag',
            default: false
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['fusion_role', 'owner_contact', 'owner_id'],
    title: 'OwnerContactCreate'
} as const;

export const OwnerContactPublicSchema = {
    properties: {
        fusion_role: {
            type: 'string',
            maxLength: 100,
            title: 'Fusion Role'
        },
        owner_contact: {
            type: 'string',
            maxLength: 100,
            title: 'Owner Contact'
        },
        contact_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Title'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        seniority: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Seniority'
        },
        strength: {
            '$ref': '#/components/schemas/ContactStrength',
            default: 'New'
        },
        last_met: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Met'
        },
        senior_flag: {
            type: 'boolean',
            title: 'Senior Flag',
            default: false
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['fusion_role', 'owner_contact', 'id', 'owner_id'],
    title: 'OwnerContactPublic'
} as const;

export const OwnerCreateSchema = {
    properties: {
        company: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Company'
        },
        owner_type: {
            '$ref': '#/components/schemas/OwnerType',
            default: 'Developer'
        },
        country: {
            type: 'string',
            maxLength: 100,
            title: 'Country'
        },
        priority: {
            '$ref': '#/components/schemas/OwnerPriority',
            default: 'Medium'
        },
        relationship: {
            '$ref': '#/components/schemas/OwnerRelationship',
            default: 'New'
        },
        catchup_status: {
            '$ref': '#/components/schemas/CatchupStatus',
            default: 'No cadence'
        },
        next_catchup: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Catchup'
        },
        assets: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assets'
        },
        financial_health: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Financial Health'
        },
        strategic_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Strategic Value'
        }
    },
    type: 'object',
    required: ['company', 'country'],
    title: 'OwnerCreate'
} as const;

export const OwnerInteractionCreateSchema = {
    properties: {
        interaction_type: {
            '$ref': '#/components/schemas/InteractionType',
            default: 'Meeting'
        },
        date: {
            type: 'string',
            maxLength: 20,
            title: 'Date'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['date', 'owner_id'],
    title: 'OwnerInteractionCreate'
} as const;

export const OwnerInteractionPublicSchema = {
    properties: {
        interaction_type: {
            '$ref': '#/components/schemas/InteractionType',
            default: 'Meeting'
        },
        date: {
            type: 'string',
            maxLength: 20,
            title: 'Date'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['date', 'id', 'owner_id'],
    title: 'OwnerInteractionPublic'
} as const;

export const OwnerPrioritySchema = {
    type: 'string',
    enum: ['Strategic', 'High', 'Medium', 'Low'],
    title: 'OwnerPriority'
} as const;

export const OwnerPublicSchema = {
    properties: {
        company: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Company'
        },
        owner_type: {
            '$ref': '#/components/schemas/OwnerType',
            default: 'Developer'
        },
        country: {
            type: 'string',
            maxLength: 100,
            title: 'Country'
        },
        priority: {
            '$ref': '#/components/schemas/OwnerPriority',
            default: 'Medium'
        },
        relationship: {
            '$ref': '#/components/schemas/OwnerRelationship',
            default: 'New'
        },
        catchup_status: {
            '$ref': '#/components/schemas/CatchupStatus',
            default: 'No cadence'
        },
        next_catchup: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Catchup'
        },
        assets: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assets'
        },
        financial_health: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Financial Health'
        },
        strategic_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Strategic Value'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        deal_count: {
            type: 'integer',
            title: 'Deal Count',
            default: 0
        },
        project_count: {
            type: 'integer',
            title: 'Project Count',
            default: 0
        },
        last_interaction: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Interaction'
        }
    },
    type: 'object',
    required: ['company', 'country', 'id'],
    title: 'OwnerPublic'
} as const;

export const OwnerRelationshipSchema = {
    type: 'string',
    enum: ['New', 'Warm', 'Strong', 'Strategic Partner', 'Risk / Unstable'],
    title: 'OwnerRelationship'
} as const;

export const OwnerTypeSchema = {
    type: 'string',
    enum: ['Developer', 'Family Office', 'REIT', 'Asset Owner', 'Institutional Investor'],
    title: 'OwnerType'
} as const;

export const OwnerUpdateSchema = {
    properties: {
        company: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company'
        },
        owner_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OwnerType'
                },
                {
                    type: 'null'
                }
            ]
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        priority: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OwnerPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        relationship: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OwnerRelationship'
                },
                {
                    type: 'null'
                }
            ]
        },
        catchup_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CatchupStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        next_catchup: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Catchup'
        },
        assets: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assets'
        },
        financial_health: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Financial Health'
        },
        strategic_value: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Strategic Value'
        }
    },
    type: 'object',
    title: 'OwnerUpdate'
} as const;

export const OwnersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OwnerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OwnersPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        country: {
            type: 'string',
            maxLength: 100,
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/APACRegion'
                },
                {
                    type: 'null'
                }
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        project_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectType'
                },
                {
                    type: 'null'
                }
            ]
        },
        keys: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Keys'
        },
        opening_target: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opening Target'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus',
            default: 'Prospect'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'country'],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        country: {
            type: 'string',
            maxLength: 100,
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/APACRegion'
                },
                {
                    type: 'null'
                }
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        project_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectType'
                },
                {
                    type: 'null'
                }
            ]
        },
        keys: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Keys'
        },
        opening_target: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opening Target'
        },
        status: {
            '$ref': '#/components/schemas/ProjectStatus',
            default: 'Prospect'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Number'
        },
        owner_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Name'
        },
        deal_count: {
            type: 'integer',
            title: 'Deal Count',
            default: 0
        },
        active_pipeline_value: {
            type: 'integer',
            title: 'Active Pipeline Value',
            default: 0
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'country', 'id', 'project_number'],
    title: 'ProjectPublic'
} as const;

export const ProjectStatusSchema = {
    type: 'string',
    enum: ['Prospect', 'Active', 'On Hold', 'Operating', 'Lost', 'Closed'],
    title: 'ProjectStatus'
} as const;

export const ProjectTypeSchema = {
    type: 'string',
    enum: ['Hotel New Build (Greenfield)', 'Hotel Re-Brand', 'Hotel Conversion (Takeover)', 'Hotel Adaptive Re-Use', 'Serviced Apartment New Build', 'Wellness / Spa Resort', 'Branded Residences'],
    title: 'ProjectType'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/APACRegion'
                },
                {
                    type: 'null'
                }
            ]
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        project_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectType'
                },
                {
                    type: 'null'
                }
            ]
        },
        keys: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Keys'
        },
        opening_target: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Opening Target'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProjectStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const StageChangeRequestSchema = {
    properties: {
        new_stage: {
            '$ref': '#/components/schemas/DealStage'
        },
        note: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Note'
        },
        next_action: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Action'
        }
    },
    type: 'object',
    required: ['new_stage', 'note'],
    title: 'StageChangeRequest'
} as const;

export const TaskCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Title'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        task_owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Owner'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            '$ref': '#/components/schemas/TaskPriority',
            default: 'Medium'
        },
        status: {
            '$ref': '#/components/schemas/TaskStatus',
            default: 'Open'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'TaskCreate'
} as const;

export const TaskPrioritySchema = {
    type: 'string',
    enum: ['High', 'Medium', 'Low'],
    title: 'TaskPriority'
} as const;

export const TaskPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Title'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        task_owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Owner'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            '$ref': '#/components/schemas/TaskPriority',
            default: 'Medium'
        },
        status: {
            '$ref': '#/components/schemas/TaskStatus',
            default: 'Open'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        is_overdue: {
            type: 'boolean',
            title: 'Is Overdue',
            default: false
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'created_by_id'],
    title: 'TaskPublic'
} as const;

export const TaskStatusSchema = {
    type: 'string',
    enum: ['Open', 'In Progress', 'Blocked', 'Done'],
    title: 'TaskStatus'
} as const;

export const TaskUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        deal_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Id'
        },
        deal_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deal Name'
        },
        task_owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Owner'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TaskStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    title: 'TaskUpdate'
} as const;

export const TasksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TasksPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'BD Manager'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'BD Manager'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['CEO', 'COO', 'BD Director', 'BD Manager', 'Legal', 'Finance', 'IT Admin'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'BD Manager'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;