// This file is auto-generated by @hey-api/openapi-ts

export type ActivitiesPublic = {
    data: Array<ActivityPublic>;
    count: number;
};

export type ActivityCreate = {
    activity_type?: ActivityType;
    date: string;
    deal_id?: (string | null);
    deal_name?: (string | null);
    note?: (string | null);
};

export type ActivityPublic = {
    activity_type?: ActivityType;
    date: string;
    deal_id?: (string | null);
    deal_name?: (string | null);
    note?: (string | null);
    id: string;
    created_by_id: string;
    created_at?: (string | null);
};

export type ActivityType = 'Meeting' | 'Dinner' | 'Site visit' | 'Phone call' | 'WhatsApp summary' | 'Proposal sent' | 'NDA signed' | 'LOI signed' | 'HMA signed' | 'Pre-opening review' | 'Other';

export type APACRegion = 'Vietnam' | 'Thailand' | 'Southeast Asia' | 'Greater China' | 'North Asia' | 'South Asia' | 'Australia / Pacific' | 'Europe' | 'Americas' | 'Middle East & Africa';

export type Body_documents_upload_document = {
    file: (Blob | File);
    name: string;
    doc_type?: string;
    permission?: string;
    deal_id?: string;
    deal_name?: string;
    project_id?: string;
    project_name?: string;
    version?: string;
    note?: string;
    is_confidential?: boolean;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BulkTaskDelete = {
    task_ids: Array<(string)>;
};

export type BulkTaskUpdate = {
    task_ids: Array<(string)>;
    status?: (TaskStatus | null);
    task_owner_id?: (string | null);
};

export type CatchupStatus = 'On track' | 'Due this week' | 'Overdue' | 'No cadence';

export type ContactStrength = 'New' | 'Warm' | 'Strong';

export type DealAuditLogPublic = {
    id: string;
    field: string;
    old_value: (string | null);
    new_value: string;
    note: (string | null);
    user_id: string;
    created_at: string;
};

export type DealCreate = {
    name: string;
    project_id?: (string | null);
    deal_type?: DealType;
    country: string;
    region?: (APACRegion | null);
    city?: (string | null);
    owner_name?: (string | null);
    brand?: (string | null);
    project_type?: (ProjectType | null);
    stage?: DealStage;
    opening_target?: (string | null);
    keys?: (number | null);
    probability?: (number | null);
    probability_source?: string;
    pipeline_value?: (number | null);
    fee_forecast?: (number | null);
    risk?: DealRisk;
    feasibility?: DealFeasibility;
    next_action?: (string | null);
    bd_owner_id?: (string | null);
};

export type DealFeasibility = 'TBD' | 'Weak' | 'Medium' | 'Strong' | 'Updated';

export type DealPublic = {
    name: string;
    project_id?: (string | null);
    deal_type?: DealType;
    country: string;
    region?: (APACRegion | null);
    city?: (string | null);
    owner_name?: (string | null);
    brand?: (string | null);
    project_type?: (ProjectType | null);
    stage?: DealStage;
    opening_target?: (string | null);
    keys?: (number | null);
    probability?: (number | null);
    probability_source?: string;
    pipeline_value?: (number | null);
    fee_forecast?: (number | null);
    risk?: DealRisk;
    feasibility?: DealFeasibility;
    next_action?: (string | null);
    id: string;
    deal_number?: (number | null);
    bd_owner_id?: (string | null);
    bd_owner_name?: (string | null);
    created_by_id: string;
    days_in_stage?: number;
    stage_changed_at?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    project_name?: (string | null);
    project_number?: (number | null);
    owner_id?: (string | null);
    feasibility_score?: (number | null);
    feasibility_recommendation?: (string | null);
    feasibility_reviewed?: boolean;
};

export type DealRisk = 'Green' | 'Amber' | 'Red';

export type DealsPublic = {
    data: Array<DealPublic>;
    count: number;
};

export type DealStage = 'Lead' | 'NDA / Qualified' | 'Feasibility' | 'Proposal' | 'Negotiation' | 'LOI Signed' | 'HMA Signed' | 'Pre-opening' | 'Opened' | 'Lost';

export type DealType = 'HMA' | 'TSA' | 'Franchise' | 'Consulting' | 'Pre-opening' | 'Other';

export type DealUpdate = {
    name?: (string | null);
    project_id?: (string | null);
    deal_type?: (string | null);
    country?: (string | null);
    region?: (APACRegion | null);
    city?: (string | null);
    owner_name?: (string | null);
    brand?: (string | null);
    project_type?: (ProjectType | null);
    opening_target?: (string | null);
    keys?: (number | null);
    probability?: (number | null);
    probability_source?: (string | null);
    pipeline_value?: (number | null);
    fee_forecast?: (number | null);
    risk?: (DealRisk | null);
    feasibility?: (DealFeasibility | null);
    next_action?: (string | null);
    bd_owner_id?: (string | null);
};

export type DocPermission = 'Internal Only' | 'Shared with Owner' | 'Restricted';

export type DocType = 'NDA' | 'Proposal' | 'Feasibility' | 'HMA Draft' | 'Contract' | 'Technical Drawings' | 'Legal Document' | 'Presentation' | 'Other';

export type DocumentPublic = {
    name: string;
    doc_type?: DocType;
    permission?: DocPermission;
    deal_id?: (string | null);
    deal_name?: (string | null);
    project_id?: (string | null);
    project_name?: (string | null);
    version?: (string | null);
    note?: (string | null);
    is_confidential?: boolean;
    id: string;
    original_filename: string;
    file_size: number;
    content_type: string;
    uploaded_by_id: string;
    uploaded_at?: (string | null);
    download_url?: (string | null);
    can_view?: boolean;
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type FeasibilityAssessmentCreate = {
    location_score: number;
    market_score: number;
    owner_readiness_score: number;
    brand_fit_score: number;
    financial_score: number;
    technical_score: number;
    strengths?: (string | null);
    concerns?: (string | null);
    competitive_landscape?: (string | null);
    deal_killers?: (string | null);
    conditions_to_proceed?: (string | null);
};

export type FeasibilityAssessmentHistory = {
    data: Array<FeasibilityAssessmentPublic>;
    count: number;
};

/**
 * Quick-edit text fields on current assessment, no version bump.
 */
export type FeasibilityAssessmentNotesUpdate = {
    strengths?: (string | null);
    concerns?: (string | null);
    competitive_landscape?: (string | null);
    deal_killers?: (string | null);
    conditions_to_proceed?: (string | null);
};

export type FeasibilityAssessmentPublic = {
    deal_id: string;
    location_score: number;
    market_score: number;
    owner_readiness_score: number;
    brand_fit_score: number;
    financial_score: number;
    technical_score: number;
    total_score?: number;
    recommendation?: string;
    strengths?: (string | null);
    concerns?: (string | null);
    competitive_landscape?: (string | null);
    deal_killers?: (string | null);
    conditions_to_proceed?: (string | null);
    id: string;
    version: number;
    is_current: boolean;
    assessed_by_id: string;
    assessed_by_name?: (string | null);
    assessed_at: (string | null);
    reviewed_by_id: (string | null);
    reviewed_by_name?: (string | null);
    reviewed_at: (string | null);
    review_note: (string | null);
};

export type FeasibilityAssessmentReview = {
    review_note?: (string | null);
};

export type FeasibilitySnapshotCreate = {
    deal_id?: (string | null);
    deal_name?: (string | null);
    label?: (string | null);
    assumptions: string;
    outputs: string;
};

export type FeasibilitySnapshotPublic = {
    id: string;
    deal_id: (string | null);
    deal_name: (string | null);
    label: (string | null);
    assumptions: string;
    outputs: string;
    created_by_id: string;
    created_at: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InteractionType = 'Meeting' | 'Dinner' | 'Site visit' | 'Phone call' | 'WhatsApp summary' | 'Proposal sent' | 'NDA signed' | 'Other';

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MasterDataCreate = {
    category: string;
    value: string;
    sort_order?: number;
};

export type MasterDataPublic = {
    id: string;
    category: string;
    value: string;
    sort_order: number;
    is_active: boolean;
};

export type Message = {
    message: string;
};

export type MilestoneCreate = {
    name: string;
    project_id?: (string | null);
    project_name?: (string | null);
    deal_id?: (string | null);
    deal_name?: (string | null);
    department?: MilestoneDept;
    milestone_owner?: (string | null);
    due_date?: (string | null);
    status?: MilestoneGate;
    blocker?: (string | null);
};

export type MilestoneDept = 'Ops' | 'IT' | 'Finance' | 'Design' | 'Legal' | 'Procurement' | 'HR' | 'Marketing';

export type MilestoneGate = 'Green' | 'Amber' | 'Red';

export type MilestonePublic = {
    name: string;
    project_id?: (string | null);
    project_name?: (string | null);
    deal_id?: (string | null);
    deal_name?: (string | null);
    department?: MilestoneDept;
    milestone_owner?: (string | null);
    due_date?: (string | null);
    status?: MilestoneGate;
    blocker?: (string | null);
    id: string;
    created_by_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type MilestonesPublic = {
    data: Array<MilestonePublic>;
    count: number;
};

export type MilestoneUpdate = {
    name?: (string | null);
    project_id?: (string | null);
    project_name?: (string | null);
    deal_id?: (string | null);
    deal_name?: (string | null);
    department?: (MilestoneDept | null);
    milestone_owner?: (string | null);
    due_date?: (string | null);
    status?: (MilestoneGate | null);
    blocker?: (string | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OwnerContactCreate = {
    fusion_role: string;
    owner_contact: string;
    contact_title?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    seniority?: (string | null);
    strength?: ContactStrength;
    last_met?: (string | null);
    senior_flag?: boolean;
    note?: (string | null);
    owner_id: string;
};

export type OwnerContactPublic = {
    fusion_role: string;
    owner_contact: string;
    contact_title?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    seniority?: (string | null);
    strength?: ContactStrength;
    last_met?: (string | null);
    senior_flag?: boolean;
    note?: (string | null);
    id: string;
    owner_id: string;
};

export type OwnerCreate = {
    company: string;
    owner_type?: OwnerType;
    country: string;
    priority?: OwnerPriority;
    relationship?: OwnerRelationship;
    catchup_status?: CatchupStatus;
    next_catchup?: (string | null);
    assets?: (string | null);
    financial_health?: (string | null);
    strategic_value?: (string | null);
};

export type OwnerInteractionCreate = {
    interaction_type?: InteractionType;
    date: string;
    note?: (string | null);
    owner_id: string;
};

export type OwnerInteractionPublic = {
    interaction_type?: InteractionType;
    date: string;
    note?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type OwnerPriority = 'Strategic' | 'High' | 'Medium' | 'Low';

export type OwnerPublic = {
    company: string;
    owner_type?: OwnerType;
    country: string;
    priority?: OwnerPriority;
    relationship?: OwnerRelationship;
    catchup_status?: CatchupStatus;
    next_catchup?: (string | null);
    assets?: (string | null);
    financial_health?: (string | null);
    strategic_value?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    deal_count?: number;
    project_count?: number;
    last_interaction?: (string | null);
};

export type OwnerRelationship = 'New' | 'Warm' | 'Strong' | 'Strategic Partner' | 'Risk / Unstable';

export type OwnersPublic = {
    data: Array<OwnerPublic>;
    count: number;
};

export type OwnerType = 'Developer' | 'Family Office' | 'REIT' | 'Asset Owner' | 'Institutional Investor';

export type OwnerUpdate = {
    company?: (string | null);
    owner_type?: (OwnerType | null);
    country?: (string | null);
    priority?: (OwnerPriority | null);
    relationship?: (OwnerRelationship | null);
    catchup_status?: (CatchupStatus | null);
    next_catchup?: (string | null);
    assets?: (string | null);
    financial_health?: (string | null);
    strategic_value?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectCreate = {
    name: string;
    owner_id?: (string | null);
    country: string;
    region?: (APACRegion | null);
    city?: (string | null);
    location_detail?: (string | null);
    google_maps_url?: (string | null);
    project_type?: (ProjectType | null);
    segment?: (string | null);
    keys?: (number | null);
    room_mix?: (string | null);
    facilities?: (string | null);
    status?: ProjectStatus;
    construction_status?: (string | null);
    design_status?: (string | null);
    legal_status?: (string | null);
    funding_status?: (string | null);
    opening_target?: (string | null);
    description?: (string | null);
};

export type ProjectPublic = {
    name: string;
    owner_id?: (string | null);
    country: string;
    region?: (APACRegion | null);
    city?: (string | null);
    location_detail?: (string | null);
    google_maps_url?: (string | null);
    project_type?: (ProjectType | null);
    segment?: (string | null);
    keys?: (number | null);
    room_mix?: (string | null);
    facilities?: (string | null);
    status?: ProjectStatus;
    construction_status?: (string | null);
    design_status?: (string | null);
    legal_status?: (string | null);
    funding_status?: (string | null);
    opening_target?: (string | null);
    description?: (string | null);
    id: string;
    project_number: (number | null);
    owner_name?: (string | null);
    deal_count?: number;
    active_pipeline_value?: number;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectStatus = 'Prospect' | 'Active' | 'On Hold' | 'Operating' | 'Lost' | 'Closed';

export type ProjectType = 'Hotel New Build (Greenfield)' | 'Hotel Re-Brand' | 'Hotel Conversion (Takeover)' | 'Hotel Adaptive Re-Use' | 'Serviced Apartment New Build' | 'Wellness / Spa Resort' | 'Branded Residences';

export type ProjectUpdate = {
    name?: (string | null);
    owner_id?: (string | null);
    country?: (string | null);
    region?: (APACRegion | null);
    city?: (string | null);
    location_detail?: (string | null);
    google_maps_url?: (string | null);
    project_type?: (ProjectType | null);
    segment?: (string | null);
    keys?: (number | null);
    room_mix?: (string | null);
    facilities?: (string | null);
    status?: (ProjectStatus | null);
    construction_status?: (string | null);
    design_status?: (string | null);
    legal_status?: (string | null);
    funding_status?: (string | null);
    opening_target?: (string | null);
    description?: (string | null);
};

export type ScorecardResponse = {
    data: Array<ScorecardRow>;
    count: number;
    avg_score: number;
    distribution: {
        [key: string]: (number);
    };
};

export type ScorecardRow = {
    assessment_id: string;
    deal_id: string;
    deal_number: (number | null);
    deal_name: string;
    stage: (string | null);
    country: (string | null);
    bd_owner_name: (string | null);
    total_score: number;
    recommendation: string;
    location_score: number;
    market_score: number;
    owner_readiness_score: number;
    brand_fit_score: number;
    financial_score: number;
    technical_score: number;
    assessed_by_name: (string | null);
    assessed_at: (string | null);
    reviewed: boolean;
    days_since_assessed: number;
};

export type StageChangeRequest = {
    new_stage: DealStage;
    note: string;
    next_action?: (string | null);
};

export type TaskCreate = {
    title: string;
    deal_id?: (string | null);
    deal_name?: (string | null);
    task_owner_id?: (string | null);
    task_owner?: (string | null);
    due_date?: (string | null);
    priority?: TaskPriority;
    status?: TaskStatus;
    note?: (string | null);
};

export type TaskPriority = 'High' | 'Medium' | 'Low';

export type TaskPublic = {
    title: string;
    deal_id?: (string | null);
    deal_name?: (string | null);
    task_owner_id?: (string | null);
    task_owner?: (string | null);
    due_date?: (string | null);
    priority?: TaskPriority;
    status?: TaskStatus;
    note?: (string | null);
    id: string;
    created_by_id: string;
    is_overdue?: boolean;
    task_owner_name?: (string | null);
    task_owner_role?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskStatus = 'Open' | 'In Progress' | 'Blocked' | 'Done';

export type TaskUpdate = {
    title?: (string | null);
    deal_id?: (string | null);
    deal_name?: (string | null);
    task_owner_id?: (string | null);
    task_owner?: (string | null);
    due_date?: (string | null);
    priority?: (TaskPriority | null);
    status?: (TaskStatus | null);
    note?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'CEO' | 'COO' | 'BD Director' | 'BD Manager' | 'Legal' | 'Finance' | 'IT Admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ActivitiesListActivitiesData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    dealId?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ActivitiesListActivitiesResponse = (ActivitiesPublic);

export type ActivitiesCreateActivityData = {
    requestBody: ActivityCreate;
};

export type ActivitiesCreateActivityResponse = (ActivityPublic);

export type ActivitiesDeleteActivityData = {
    id: string;
};

export type ActivitiesDeleteActivityResponse = (Message);

export type DealsListDealsData = {
    bdOwnerId?: (string | null);
    country?: (string | null);
    feasibility?: (DealFeasibility | null);
    limit?: number;
    region?: (APACRegion | null);
    risk?: (DealRisk | null);
    search?: (string | null);
    skip?: number;
    stage?: (DealStage | null);
};

export type DealsListDealsResponse = (DealsPublic);

export type DealsCreateDealData = {
    requestBody: DealCreate;
};

export type DealsCreateDealResponse = (DealPublic);

export type DealsGetDealData = {
    id: string;
};

export type DealsGetDealResponse = (DealPublic);

export type DealsUpdateDealData = {
    id: string;
    requestBody: DealUpdate;
};

export type DealsUpdateDealResponse = (DealPublic);

export type DealsDeleteDealData = {
    id: string;
};

export type DealsDeleteDealResponse = (Message);

export type DealsChangeStageData = {
    id: string;
    requestBody: StageChangeRequest;
};

export type DealsChangeStageResponse = (DealPublic);

export type DealsGetDealAuditData = {
    id: string;
};

export type DealsGetDealAuditResponse = (Array<DealAuditLogPublic>);

export type DocumentsListDocumentsData = {
    dealId?: (string | null);
    docType?: (DocType | null);
    limit?: number;
    permission?: (DocPermission | null);
    projectId?: (string | null);
    search?: (string | null);
    skip?: number;
};

export type DocumentsListDocumentsResponse = (DocumentsPublic);

export type DocumentsUploadDocumentData = {
    formData: Body_documents_upload_document;
};

export type DocumentsUploadDocumentResponse = (DocumentPublic);

export type DocumentsServeLocalFileData = {
    key: string;
};

export type DocumentsServeLocalFileResponse = (unknown);

export type DocumentsToggleConfidentialData = {
    id: string;
};

export type DocumentsToggleConfidentialResponse = (DocumentPublic);

export type DocumentsDeleteDocumentData = {
    id: string;
};

export type DocumentsDeleteDocumentResponse = (Message);

export type FeasibilityListSnapshotsData = {
    dealId?: (string | null);
    limit?: number;
};

export type FeasibilityListSnapshotsResponse = (Array<FeasibilitySnapshotPublic>);

export type FeasibilitySaveSnapshotData = {
    requestBody: FeasibilitySnapshotCreate;
};

export type FeasibilitySaveSnapshotResponse = (FeasibilitySnapshotPublic);

export type FeasibilityPipelineScorecardData = {
    recommendation?: (string | null);
    reviewedOnly?: boolean;
};

export type FeasibilityPipelineScorecardResponse = (ScorecardResponse);

export type FeasibilityDeleteSnapshotData = {
    id: string;
};

export type FeasibilityDeleteSnapshotResponse = (Message);

export type FeasibilityAssessmentGetCurrentAssessmentData = {
    dealId: string;
};

export type FeasibilityAssessmentGetCurrentAssessmentResponse = ((FeasibilityAssessmentPublic | null));

export type FeasibilityAssessmentCreateAssessmentData = {
    dealId: string;
    requestBody: FeasibilityAssessmentCreate;
};

export type FeasibilityAssessmentCreateAssessmentResponse = (FeasibilityAssessmentPublic);

export type FeasibilityAssessmentListAssessmentHistoryData = {
    dealId: string;
};

export type FeasibilityAssessmentListAssessmentHistoryResponse = (FeasibilityAssessmentHistory);

export type FeasibilityAssessmentEditAssessmentNotesData = {
    dealId: string;
    requestBody: FeasibilityAssessmentNotesUpdate;
};

export type FeasibilityAssessmentEditAssessmentNotesResponse = (FeasibilityAssessmentPublic);

export type FeasibilityAssessmentReviewAssessmentData = {
    assessmentId: string;
    dealId: string;
    requestBody: FeasibilityAssessmentReview;
};

export type FeasibilityAssessmentReviewAssessmentResponse = (FeasibilityAssessmentPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MasterDataListAllResponse = (Array<MasterDataPublic>);

export type MasterDataCreateEntryData = {
    requestBody: MasterDataCreate;
};

export type MasterDataCreateEntryResponse = (MasterDataPublic);

export type MasterDataListByCategoryData = {
    activeOnly?: boolean;
    category: string;
};

export type MasterDataListByCategoryResponse = (Array<MasterDataPublic>);

export type MasterDataUpdateEntryData = {
    id: string;
    isActive?: (boolean | null);
    sortOrder?: (number | null);
    value?: (string | null);
};

export type MasterDataUpdateEntryResponse = (MasterDataPublic);

export type MasterDataDeleteEntryData = {
    id: string;
};

export type MasterDataDeleteEntryResponse = (Message);

export type MilestonesListMilestonesData = {
    dealId?: (string | null);
    department?: (MilestoneDept | null);
    limit?: number;
    projectId?: (string | null);
    search?: (string | null);
    skip?: number;
    status?: (MilestoneGate | null);
};

export type MilestonesListMilestonesResponse = (MilestonesPublic);

export type MilestonesCreateMilestoneData = {
    requestBody: MilestoneCreate;
};

export type MilestonesCreateMilestoneResponse = (MilestonePublic);

export type MilestonesUpdateMilestoneData = {
    id: string;
    requestBody: MilestoneUpdate;
};

export type MilestonesUpdateMilestoneResponse = (MilestonePublic);

export type MilestonesDeleteMilestoneData = {
    id: string;
};

export type MilestonesDeleteMilestoneResponse = (Message);

export type OwnersListOwnersData = {
    catchupStatus?: (CatchupStatus | null);
    limit?: number;
    ownerType?: (OwnerType | null);
    relationship?: (OwnerRelationship | null);
    search?: (string | null);
    skip?: number;
};

export type OwnersListOwnersResponse = (OwnersPublic);

export type OwnersCreateOwnerData = {
    requestBody: OwnerCreate;
};

export type OwnersCreateOwnerResponse = (OwnerPublic);

export type OwnersGetOwnerData = {
    id: string;
};

export type OwnersGetOwnerResponse = (OwnerPublic);

export type OwnersUpdateOwnerData = {
    id: string;
    requestBody: OwnerUpdate;
};

export type OwnersUpdateOwnerResponse = (OwnerPublic);

export type OwnersDeleteOwnerData = {
    id: string;
};

export type OwnersDeleteOwnerResponse = (Message);

export type OwnersListContactsData = {
    id: string;
};

export type OwnersListContactsResponse = (Array<OwnerContactPublic>);

export type OwnersAddContactData = {
    id: string;
    requestBody: OwnerContactCreate;
};

export type OwnersAddContactResponse = (OwnerContactPublic);

export type OwnersListInteractionsData = {
    id: string;
};

export type OwnersListInteractionsResponse = (Array<OwnerInteractionPublic>);

export type OwnersAddInteractionData = {
    id: string;
    requestBody: OwnerInteractionCreate;
};

export type OwnersAddInteractionResponse = (OwnerInteractionPublic);

export type OwnersListOwnerProjectsData = {
    id: string;
};

export type OwnersListOwnerProjectsResponse = (unknown);

export type OwnersListOwnerDealsData = {
    id: string;
};

export type OwnersListOwnerDealsResponse = (unknown);

export type OwnersDeleteContactData = {
    contactId: string;
};

export type OwnersDeleteContactResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsListProjectsData = {
    country?: (string | null);
    limit?: number;
    ownerId?: (string | null);
    search?: (string | null);
    skip?: number;
    status?: (ProjectStatus | null);
};

export type ProjectsListProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    id: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type ProjectsListProjectDealsData = {
    id: string;
};

export type ProjectsListProjectDealsResponse = (unknown);

export type ProjectsListProjectDocumentsData = {
    id: string;
};

export type ProjectsListProjectDocumentsResponse = (unknown);

export type ProjectsListProjectMilestonesData = {
    id: string;
};

export type ProjectsListProjectMilestonesResponse = (unknown);

export type SeedLoadSeedDataData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type SeedLoadSeedDataResponse = (Message);

export type SeedClearAllDataResponse = (Message);

export type TasksListTasksData = {
    dealId?: (string | null);
    dueFrom?: (string | null);
    dueTo?: (string | null);
    hideArchived?: boolean;
    limit?: number;
    overdueOnly?: boolean;
    search?: (string | null);
    skip?: number;
    status?: (TaskStatus | null);
    taskOwnerId?: (string | null);
};

export type TasksListTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksBulkUpdateTasksData = {
    requestBody: BulkTaskUpdate;
};

export type TasksBulkUpdateTasksResponse = (Message);

export type TasksBulkDeleteTasksData = {
    requestBody: BulkTaskDelete;
};

export type TasksBulkDeleteTasksResponse = (Message);

export type TasksUpdateTaskData = {
    id: string;
    requestBody: TaskUpdate;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    id: string;
};

export type TasksDeleteTaskResponse = (Message);

export type UsersListTeamResponse = (UsersPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);