// This file is auto-generated by @hey-api/openapi-ts

export type APACRegion = 'Vietnam' | 'Thailand' | 'Southeast Asia' | 'Greater China' | 'North Asia' | 'South Asia' | 'Australia / Pacific' | 'Europe' | 'Americas' | 'Middle East & Africa';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DealAuditLogPublic = {
    id: string;
    field: string;
    old_value: (string | null);
    new_value: string;
    note: (string | null);
    user_id: string;
    created_at: string;
};

export type DealCreate = {
    name: string;
    country: string;
    region?: (APACRegion | null);
    city?: (string | null);
    owner_name?: (string | null);
    brand?: (string | null);
    project_type?: (ProjectType | null);
    stage?: DealStage;
    opening_target?: (string | null);
    keys?: (number | null);
    probability?: (number | null);
    pipeline_value?: (number | null);
    fee_forecast?: (number | null);
    risk?: DealRisk;
    feasibility?: DealFeasibility;
    next_action?: (string | null);
    bd_owner_id?: (string | null);
};

export type DealFeasibility = 'TBD' | 'Weak' | 'Medium' | 'Strong' | 'Updated';

export type DealPublic = {
    name: string;
    country: string;
    region?: (APACRegion | null);
    city?: (string | null);
    owner_name?: (string | null);
    brand?: (string | null);
    project_type?: (ProjectType | null);
    stage?: DealStage;
    opening_target?: (string | null);
    keys?: (number | null);
    probability?: (number | null);
    pipeline_value?: (number | null);
    fee_forecast?: (number | null);
    risk?: DealRisk;
    feasibility?: DealFeasibility;
    next_action?: (string | null);
    id: string;
    deal_number?: (number | null);
    bd_owner_id?: (string | null);
    bd_owner_name?: (string | null);
    created_by_id: string;
    days_in_stage?: number;
    stage_changed_at?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type DealRisk = 'Green' | 'Amber' | 'Red';

export type DealsPublic = {
    data: Array<DealPublic>;
    count: number;
};

export type DealStage = 'Lead' | 'NDA / Qualified' | 'Feasibility' | 'Proposal' | 'Negotiation' | 'LOI Signed' | 'HMA Signed' | 'Pre-opening' | 'Opened' | 'Lost';

export type DealUpdate = {
    name?: (string | null);
    country?: (string | null);
    region?: (APACRegion | null);
    city?: (string | null);
    owner_name?: (string | null);
    brand?: (string | null);
    project_type?: (ProjectType | null);
    opening_target?: (string | null);
    keys?: (number | null);
    probability?: (number | null);
    pipeline_value?: (number | null);
    fee_forecast?: (number | null);
    risk?: (DealRisk | null);
    feasibility?: (DealFeasibility | null);
    next_action?: (string | null);
    bd_owner_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProjectType = 'Hotel New Build (Greenfield)' | 'Hotel Re-Brand' | 'Hotel Conversion (Takeover)' | 'Hotel Adaptive Re-Use' | 'Serviced Apartment New Build' | 'Wellness / Spa Resort' | 'Branded Residences';

export type StageChangeRequest = {
    new_stage: DealStage;
    note: string;
    next_action?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'CEO' | 'COO' | 'BD Director' | 'BD Manager' | 'Legal' | 'Finance' | 'IT Admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type DealsListDealsData = {
    bdOwnerId?: (string | null);
    country?: (string | null);
    feasibility?: (DealFeasibility | null);
    limit?: number;
    region?: (APACRegion | null);
    risk?: (DealRisk | null);
    search?: (string | null);
    skip?: number;
    stage?: (DealStage | null);
};

export type DealsListDealsResponse = (DealsPublic);

export type DealsCreateDealData = {
    requestBody: DealCreate;
};

export type DealsCreateDealResponse = (DealPublic);

export type DealsGetDealData = {
    id: string;
};

export type DealsGetDealResponse = (DealPublic);

export type DealsUpdateDealData = {
    id: string;
    requestBody: DealUpdate;
};

export type DealsUpdateDealResponse = (DealPublic);

export type DealsDeleteDealData = {
    id: string;
};

export type DealsDeleteDealResponse = (Message);

export type DealsChangeStageData = {
    id: string;
    requestBody: StageChangeRequest;
};

export type DealsChangeStageResponse = (DealPublic);

export type DealsGetDealAuditData = {
    id: string;
};

export type DealsGetDealAuditResponse = (Array<DealAuditLogPublic>);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);