/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProjectsRouteImport } from './routes/_layout/projects'
import { Route as LayoutPreopeningRouteImport } from './routes/_layout/preopening'
import { Route as LayoutOwnersRouteImport } from './routes/_layout/owners'
import { Route as LayoutFeasibilityRouteImport } from './routes/_layout/feasibility'
import { Route as LayoutDocumentsRouteImport } from './routes/_layout/documents'
import { Route as LayoutDealsRouteImport } from './routes/_layout/deals'
import { Route as LayoutActivitiesRouteImport } from './routes/_layout/activities'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout/projects_.$projectId'
import { Route as LayoutOwnersOwnerIdRouteImport } from './routes/_layout/owners_.$ownerId'
import { Route as LayoutDealsDealIdRouteImport } from './routes/_layout/deals_.$dealId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPreopeningRoute = LayoutPreopeningRouteImport.update({
  id: '/preopening',
  path: '/preopening',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnersRoute = LayoutOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeasibilityRoute = LayoutFeasibilityRouteImport.update({
  id: '/feasibility',
  path: '/feasibility',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsRoute = LayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDealsRoute = LayoutDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesRoute = LayoutActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnersOwnerIdRoute = LayoutOwnersOwnerIdRouteImport.update({
  id: '/owners_/$ownerId',
  path: '/owners/$ownerId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDealsDealIdRoute = LayoutDealsDealIdRouteImport.update({
  id: '/deals_/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activities': typeof LayoutActivitiesRoute
  '/deals': typeof LayoutDealsRoute
  '/documents': typeof LayoutDocumentsRoute
  '/feasibility': typeof LayoutFeasibilityRoute
  '/owners': typeof LayoutOwnersRoute
  '/preopening': typeof LayoutPreopeningRoute
  '/projects': typeof LayoutProjectsRoute
  '/settings': typeof LayoutSettingsRoute
  '/deals/$dealId': typeof LayoutDealsDealIdRoute
  '/owners/$ownerId': typeof LayoutOwnersOwnerIdRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activities': typeof LayoutActivitiesRoute
  '/deals': typeof LayoutDealsRoute
  '/documents': typeof LayoutDocumentsRoute
  '/feasibility': typeof LayoutFeasibilityRoute
  '/owners': typeof LayoutOwnersRoute
  '/preopening': typeof LayoutPreopeningRoute
  '/projects': typeof LayoutProjectsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/deals/$dealId': typeof LayoutDealsDealIdRoute
  '/owners/$ownerId': typeof LayoutOwnersOwnerIdRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/activities': typeof LayoutActivitiesRoute
  '/_layout/deals': typeof LayoutDealsRoute
  '/_layout/documents': typeof LayoutDocumentsRoute
  '/_layout/feasibility': typeof LayoutFeasibilityRoute
  '/_layout/owners': typeof LayoutOwnersRoute
  '/_layout/preopening': typeof LayoutPreopeningRoute
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/deals_/$dealId': typeof LayoutDealsDealIdRoute
  '/_layout/owners_/$ownerId': typeof LayoutOwnersOwnerIdRoute
  '/_layout/projects_/$projectId': typeof LayoutProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/activities'
    | '/deals'
    | '/documents'
    | '/feasibility'
    | '/owners'
    | '/preopening'
    | '/projects'
    | '/settings'
    | '/deals/$dealId'
    | '/owners/$ownerId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/activities'
    | '/deals'
    | '/documents'
    | '/feasibility'
    | '/owners'
    | '/preopening'
    | '/projects'
    | '/settings'
    | '/'
    | '/deals/$dealId'
    | '/owners/$ownerId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/activities'
    | '/_layout/deals'
    | '/_layout/documents'
    | '/_layout/feasibility'
    | '/_layout/owners'
    | '/_layout/preopening'
    | '/_layout/projects'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/deals_/$dealId'
    | '/_layout/owners_/$ownerId'
    | '/_layout/projects_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/preopening': {
      id: '/_layout/preopening'
      path: '/preopening'
      fullPath: '/preopening'
      preLoaderRoute: typeof LayoutPreopeningRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/owners': {
      id: '/_layout/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof LayoutOwnersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feasibility': {
      id: '/_layout/feasibility'
      path: '/feasibility'
      fullPath: '/feasibility'
      preLoaderRoute: typeof LayoutFeasibilityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents': {
      id: '/_layout/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof LayoutDocumentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/deals': {
      id: '/_layout/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof LayoutDealsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities': {
      id: '/_layout/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof LayoutActivitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects_/$projectId': {
      id: '/_layout/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/owners_/$ownerId': {
      id: '/_layout/owners_/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/owners/$ownerId'
      preLoaderRoute: typeof LayoutOwnersOwnerIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/deals_/$dealId': {
      id: '/_layout/deals_/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof LayoutDealsDealIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutActivitiesRoute: typeof LayoutActivitiesRoute
  LayoutDealsRoute: typeof LayoutDealsRoute
  LayoutDocumentsRoute: typeof LayoutDocumentsRoute
  LayoutFeasibilityRoute: typeof LayoutFeasibilityRoute
  LayoutOwnersRoute: typeof LayoutOwnersRoute
  LayoutPreopeningRoute: typeof LayoutPreopeningRoute
  LayoutProjectsRoute: typeof LayoutProjectsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDealsDealIdRoute: typeof LayoutDealsDealIdRoute
  LayoutOwnersOwnerIdRoute: typeof LayoutOwnersOwnerIdRoute
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutActivitiesRoute: LayoutActivitiesRoute,
  LayoutDealsRoute: LayoutDealsRoute,
  LayoutDocumentsRoute: LayoutDocumentsRoute,
  LayoutFeasibilityRoute: LayoutFeasibilityRoute,
  LayoutOwnersRoute: LayoutOwnersRoute,
  LayoutPreopeningRoute: LayoutPreopeningRoute,
  LayoutProjectsRoute: LayoutProjectsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDealsDealIdRoute: LayoutDealsDealIdRoute,
  LayoutOwnersOwnerIdRoute: LayoutOwnersOwnerIdRoute,
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
